//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebErpExt5.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebErpExt5.resources.ProductLabels", typeof(ProductLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible para venta.
        /// </summary>
        public static string AvailableForSale {
            get {
                return ResourceManager.GetString("AvailableForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas bancarias.
        /// </summary>
        public static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturación.
        /// </summary>
        public static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajas.
        /// </summary>
        public static string CashRegisters {
            get {
                return ResourceManager.GetString("CashRegisters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conceptos Cobro/Pago.
        /// </summary>
        public static string ChargePaymentConcepts {
            get {
                return ResourceManager.GetString("ChargePaymentConcepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formas de Cobro/Pago.
        /// </summary>
        public static string ChargePaymentMethod {
            get {
                return ResourceManager.GetString("ChargePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentes comerciales.
        /// </summary>
        public static string ComercialAgents {
            get {
                return ResourceManager.GetString("ComercialAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ha sido creado correctamente.
        /// </summary>
        public static string CreationSuccessMessage {
            get {
                return ResourceManager.GetString("CreationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creación exitosa.
        /// </summary>
        public static string CreationSuccessTitle {
            get {
                return ResourceManager.GetString("CreationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM.
        /// </summary>
        public static string Crm {
            get {
                return ResourceManager.GetString("Crm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está seguro que desea borrar el registro?.
        /// </summary>
        public static string DeleteConfirmContent {
            get {
                return ResourceManager.GetString("DeleteConfirmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar borrado.
        /// </summary>
        public static string DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositorio de documentos.
        /// </summary>
        public static string DocumentsRepository {
            get {
                return ResourceManager.GetString("DocumentsRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro ha sido editado correctamente.
        /// </summary>
        public static string EditionSuccessMessage {
            get {
                return ResourceManager.GetString("EditionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edición exitosa.
        /// </summary>
        public static string EditionSuccessTitle {
            get {
                return ResourceManager.GetString("EditionSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de vencimiento.
        /// </summary>
        public static string ExpirationTypes {
            get {
                return ResourceManager.GetString("ExpirationTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familias.
        /// </summary>
        public static string Families {
            get {
                return ResourceManager.GetString("Families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series de factura.
        /// </summary>
        public static string InvoiceSeries {
            get {
                return ResourceManager.GetString("InvoiceSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de factura.
        /// </summary>
        public static string InvoiceTypes {
            get {
                return ResourceManager.GetString("InvoiceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de productos.
        /// </summary>
        public static string ListOfProducts {
            get {
                return ResourceManager.GetString("ListOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción larga.
        /// </summary>
        public static string LongDescription {
            get {
                return ResourceManager.GetString("LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de medida.
        /// </summary>
        public static string MeasureUnity {
            get {
                return ResourceManager.GetString("MeasureUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de medida.
        /// </summary>
        public static string MeasurmentUnits {
            get {
                return ResourceManager.GetString("MeasurmentUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de oferta.
        /// </summary>
        public static string OfferTypes {
            get {
                return ResourceManager.GetString("OfferTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socios.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes potenciales.
        /// </summary>
        public static string PotentialClients {
            get {
                return ResourceManager.GetString("PotentialClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifas.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        public static string ProductFamily {
            get {
                return ResourceManager.GetString("ProductFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectos.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoraciones de proveedores.
        /// </summary>
        public static string ProviderRatings {
            get {
                return ResourceManager.GetString("ProviderRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de proveedor.
        /// </summary>
        public static string ProviderTypes {
            get {
                return ResourceManager.GetString("ProviderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventas.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción breve.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuestos.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportistas.
        /// </summary>
        public static string Transporters {
            get {
                return ResourceManager.GetString("Transporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almacén.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
