//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string OrderCode { get; set; }
        public string Reference { get; set; }
        public int ChargeMethodId { get; set; }
        public int PaymentDueDateTypeId { get; set; }
        public string DeliveryAddress { get; set; }
        public string ComercialAgent { get; set; }
    
        public virtual ChargeMethod ChargeMethod { get; set; }
    }
}
