//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime EmisionDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public string BillNumber { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal AmountToCharge { get; set; }
        public int SaleStateId { get; set; }
        public int SaleCategoryId { get; set; }
        public int BillTypeId { get; set; }
        public string Observations { get; set; }
        public int ClientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual SaleState SaleState { get; set; }
        public virtual SaleCategory SaleCategory { get; set; }
        public virtual BillType BillType { get; set; }
        public virtual Client Client { get; set; }
    }
}
