using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AM.DAL
{
    public class Store : AuditableEntity
    {
        [Key]
		public int StoreId { get; set; }
		public int CorpStoreId { get; set; }
		public string StoreCode { get; set; }
		public string StoreName { get; set; }
		public string BrandCode { get; set; }
		public string Address1 { get; set; }
		public string Address2 { get; set; }
		public string City { get; set; }
		public string CountryCode { get; set; }
		public string StateName { get; set; }
		public string Zip { get; set; }
		public string Phone { get; set; }
		public string TollFreePhone { get; set; }
		public string Fax { get; set; }
		public string Email { get; set; }
		public string Website { get; set; }
		public string CurrencyCode { get; set; }
		public bool ExcludePreprinted { get; set; }
		public bool InvoiceDisclaimer { get; set; }
		public string SiteId { get; set; }
		public string DefCountryCode { get; set; }
		public string DefStateName { get; set; }
		public string DefAreaCode { get; set; }
		public string GatewayCity { get; set; }
		public short DocDueDays { get; set; }
		public short BonVoyageDays { get; set; }
		public short PostCruiseDays { get; set; }
		public short AirDevDays { get; set; }
		public short GiftOrderDays { get; set; }
		public short DpstOffsetDays { get; set; }
		public short FnlPymtOffsetDays { get; set; }
		public int? CheckSeqNum { get; set; }
		public bool Dp2vManualChecks { get; set; }
		public bool Dp2vPrintCheck { get; set; }
		public bool Dp2vStoreCc { get; set; }
		public bool Dp2cPrintCheck { get; set; }
		public short? CheckTypeCode { get; set; }
		public string SecurityDtDesc { get; set; }
		public bool BankCard { get; set; }
		public bool RecPayInvoice { get; set; }
		public bool Invoice2ndPage { get; set; }
		public bool InvoicePreprinted { get; set; }
		public bool DisbPayMultires { get; set; }
		public bool IncludePortTax { get; set; }
		public bool UsLogo { get; set; }
		public bool AddonGridProp { get; set; }
		public string InvoiceInfoDesc { get; set; }
		public string FinalInfoDesc { get; set; }
		public string CancelInfoDesc { get; set; }
		public string NonBookInfoDesc { get; set; }
		public string StandardGrpInvInfo { get; set; }
		public string NonCruiseGrpInvInfo { get; set; }
		public bool Deleted { get; set; }
		public bool Active { get; set; }
		public DateTime? ImportDate { get; set; }
		public string InvoiceHeader1 { get; set; }
		public string InvoiceHeader2 { get; set; }
		public bool ShareGroups { get; set; }
		public DateTime? ContractBeginDate { get; set; }
		public DateTime? ContractEndDate { get; set; }
		public decimal? RenewalFeeAmt { get; set; }
		public DateTime? RenewalDate { get; set; }
		public bool? Dp2vCheckRequest { get; set; }
		public string ReportsCurrencyCode { get; set; }
		public string ShortStoreName { get; set; }
		public string PitAgencyId { get; set; }
		public string InvoiceStoreName { get; set; }
		public bool? DocDue { get; set; }
		public bool? BonVoyage { get; set; }
		public bool? PostCruise { get; set; }
		public bool? AirDev { get; set; }
		public bool? GiftOrder { get; set; }
		public string DefCounselorLogin { get; set; }
		public string CounselorReminderVdd { get; set; }
		public string CounselorReminderCdd { get; set; }
		public string CounselorReminderVfp { get; set; }
		public string CounselorReminderCfp { get; set; }
		public string CounselorReminderDd { get; set; }
		public string CounselorReminderBvc { get; set; }
		public string CounselorReminderAdc { get; set; }
		public string CounselorReminderGc { get; set; }
		public string CounselorReminderPcc { get; set; }
		public bool InvLineItemDet { get; set; }
		public bool InvPaymentDet { get; set; }
		public bool InvTravelDet { get; set; }
		public string OnlineBookingsTitle { get; set; }
		public string OnlineBookingsEmail { get; set; }
		public bool NcoaImports { get; set; }
		public string EmailSyncId { get; set; }
		public bool? CurrChgWarning { get; set; }
		public bool MktgOptInEmail { get; set; }
		public bool MktgOptInPrinted { get; set; }
		public string SotRegistration { get; set; }
		public string ExSmcLogin { get; set; }
		public bool Demo { get; set; }
		public string HeaderCode { get; set; }
		public bool DefaultSga { get; set; }
		public bool EnableCentralized { get; set; }
		public decimal? RoyaltyReportPrct { get; set; }
		public string ShoreExcGroupId { get; set; }
		public bool ShoreExcPushDown { get; set; }
		public bool EnableSabre { get; set; }
		public bool? ForceCentralized { get; set; }
		public bool EnableSabrePymts { get; set; }
		public bool IncludePolicyFee { get; set; }
		public string DefSabreCityCode { get; set; }
		public bool EnableBranches { get; set; }
		public bool EnableCcspQueue { get; set; }
		public bool DefaultCcspQueue { get; set; }
		public bool EnableUccvQueue { get; set; }
		public bool DefaultUccvQueue { get; set; }
		public bool ManagePendingTrans { get; set; }
		public bool EnableUnappliedComm { get; set; }
		public string DeclinedTransactionEmails { get; set; }
		public string SecCurrencyCode { get; set; }
		public decimal? ToPriCurrencyMultiplier { get; set; }
		public decimal? ToSecCurrencyMultiplier { get; set; }
		public bool? ShareCorporateGroups { get; set; }
		public bool? ShareChvGroups { get; set; }
		public string CounselorReminderGrd { get; set; }
		public bool GiftReminderDefaultItem { get; set; }
		public int? InvoiceLogoId { get; set; }
		public bool LookupDeletedCutomers { get; set; }
		public bool? AllowStorePaymentWithOpenVbal { get; set; }
		public bool EnableGiftManagement { get; set; }
		public bool? EnableCustomerAccounts { get; set; }
		public int? StoreVendorId { get; set; }
		public bool? PublicasterExport { get; set; }
		public int? AbsorbDepartmentId { get; set; }
		public string InsuranceDisclaimerDesc { get; set; }
		public bool HideCentralized { get; set; }
		public bool EnableGrpSegments { get; set; }
		public bool CeExport { get; set; }
		public bool EnableQualityCheck { get; set; }
		public string PublicasterExportFilename { get; set; }
		public string VirtuosoBranchCode { get; set; }
		public bool InterfaceVirtuoso { get; set; }
		public string AcctBillingCode { get; set; }
		public string AcctBuCode { get; set; }
		public string AcctRegionCode { get; set; }
		public string AcctGrossUsdAccountCode { get; set; }
		public string AcctGrossCadAccountCode { get; set; }
		public string AcctGrossTypeCode { get; set; }
		public string AcctGrossDeptCode { get; set; }
		public string AcctApUsdAccountCode { get; set; }
		public string AcctApCadAccountCode { get; set; }
		public string AcctApTypeCode { get; set; }
		public string AcctApDeptCode { get; set; }
		public string AcctRevenueUsdAccountCode { get; set; }
		public string AcctRevenueCadAccountCode { get; set; }
		public string AcctRevenueTypeCode { get; set; }
		public string AcctRevenueDeptCode { get; set; }
		public int? IataId { get; set; }
		public bool EnableCePrinted { get; set; }
		public string RevenuePymtRuleCode { get; set; }
		public bool GstTrans { get; set; }
		public bool GstPricings { get; set; }
		public decimal? GstPricingsPrct { get; set; }
		public int? DefGlAccountId { get; set; }
		public bool DisableCashPayments { get; set; }
		public string AgressoCode { get; set; }
		public string ServiceFeesName { get; set; }
		public string PhotoLink { get; set; }
		public bool ExpressResDefQuoted { get; set; }
		public string StoreLegalName { get; set; }
		public string StoreDba { get; set; }
		public string EntityType { get; set; }
		public string TaxIdType { get; set; }
		public string TaxIdNumber { get; set; }
		public string UsdRoutingNumber { get; set; }
		public string UsdAccountNumber { get; set; }
		public string CadRoutingNumber { get; set; }
		public string CadAccountNumber { get; set; }
		public int? StoreFileId { get; set; }
		public int? StorePhotoId { get; set; }
		public string PublicHeaderUrl { get; set; }
		public string PublicFooterUrl { get; set; }
		public bool EnableGroupRegistration { get; set; }
		public bool EnableOnlinePayments { get; set; }
		public string AcctApBuCode { get; set; }
		public string AcctRevenueBuCode { get; set; }
		public string AcctGrossDkCode { get; set; }
		public string AcctApDkCode { get; set; }
		public string AcctRevenueDkCode { get; set; }
		public string AcctMatcode { get; set; }
		public bool EnableGroupCmsMgmt { get; set; }
		public string GrpLandingPageUrl { get; set; }
		public bool GrpEnableRoommateMatching { get; set; }
		public string GrpRoommateDisclosure { get; set; }
		public string PublicHeaderGrpRegUrl { get; set; }
		public string PublicFooterGrpRegUrl { get; set; }
		public decimal? DefCustBudgetFromAmt { get; set; }
		public decimal? DefCustBudgetToAmt { get; set; }
		public short? DefCustDurationFrom { get; set; }
		public short? DefCustDurationTo { get; set; }
		public bool EnableCruisepro { get; set; }
		public string GrpCustomConfirmUrl { get; set; }
		public bool ShoreExcBranch { get; set; }
		public string PromoPagePreviewUrl { get; set; }
		public string OnlinePaymentDisclosure { get; set; }
		public bool Cra { get; set; }
		public string CraNumber { get; set; }
		public string MktgOptInPrintType { get; set; }
		public int? EngagementLogoId { get; set; }
		public bool FullVersion { get; set; }
		public bool HideSharedGroups { get; set; }
		public bool LeadRequireDeparture { get; set; }
		public bool LeadRequireDestination { get; set; }
		public bool LeadRequireVendor { get; set; }
		public bool EnableLeadRequest { get; set; }
		public bool Virtuoso { get; set; }
		public bool RequireOptoutReason { get; set; }
		public bool AllowOfferedStatus { get; set; }

		[ForeignKey("BrandCode")]
        public virtual Brand Brand { get; set; }
        [ForeignKey("IataId")]
        public virtual IATA Iata { get; set; }
    }
}